/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import logika.Kontroler;
import domen.Takmicenje;

/**
 *
 * @author Nemanja
 */
public class DialogTakmicenje extends javax.swing.JDialog {
    
    private Takmicenje t;
    /**
     * Creates new form DialogTakmicenje
     */
    public DialogTakmicenje(Takmicenje t,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.t=t;
        if(t!=null){
            btnDodaj1.setVisible(false);
            tfNazivTak.setText(t.getNazivTakm());
        }
        else btnIzmeni.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDodaj1 = new javax.swing.JButton();
        btnOdustani1 = new javax.swing.JButton();
        tfNazivTak = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        btnDodaj1.setBackground(new java.awt.Color(255, 204, 0));
        btnDodaj1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDodaj1.setText("Dodaj takmičenje");
        btnDodaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodaj1ActionPerformed(evt);
            }
        });

        btnOdustani1.setBackground(new java.awt.Color(255, 204, 0));
        btnOdustani1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOdustani1.setText("Odustani");
        btnOdustani1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustani1ActionPerformed(evt);
            }
        });

        tfNazivTak.setBackground(new java.awt.Color(255, 255, 204));

        lblid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblid.setText("Naziv takmičenja");

        btnIzmeni.setBackground(new java.awt.Color(255, 204, 0));
        btnIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIzmeni.setText("Azuriraj takmičenje");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblid)
                        .addGap(18, 18, 18)
                        .addComponent(tfNazivTak, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOdustani1)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(tfNazivTak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnDodaj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOdustani1)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodaj1ActionPerformed
        Takmicenje tak = new Takmicenje(tfNazivTak.getText());
        Kontroler.getInstance().dodajTakmicenje(tak);
        JOptionPane.showMessageDialog(this, "Uspesno ste dodali takmicenje", "Dodavanje uspesno", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnDodaj1ActionPerformed

    private void btnOdustani1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustani1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustani1ActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        Takmicenje tak = new Takmicenje(t.getIdTakmicenja(), tfNazivTak.getText());    
        Kontroler.getInstance().izmeniTakmicenje(tak);
        JOptionPane.showMessageDialog(this, "Uspesno ste izmenili takmicenje", "Izmena uspesna", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnIzmeniActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj1;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdustani1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField tfNazivTak;
    // End of variables declaration//GEN-END:variables
}
