/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import domen.*;
import java.util.List;
import logika.Kontroler;

/**
 *
 * @author Nemanja
 */
public class DijalogLokTakm extends javax.swing.JDialog {

    /**
     * Creates new form DijalogLokTakm
     */
    public DijalogLokTakm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniComboSc();
        popuniComboTakmicenja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnDodaj4 = new javax.swing.JButton();
        btnOdustani1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboSC = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboTakmicenje = new javax.swing.JComboBox<>();
        lblid = new javax.swing.JLabel();
        tfGodina = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        btnDodaj4.setBackground(new java.awt.Color(255, 204, 0));
        btnDodaj4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDodaj4.setText("Dodaj lokaciju takmičenja");
        btnDodaj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodaj4ActionPerformed(evt);
            }
        });

        btnOdustani1.setBackground(new java.awt.Color(255, 204, 0));
        btnOdustani1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOdustani1.setText("Odustani");
        btnOdustani1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustani1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Sportski centar:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Takmičenje:");

        comboTakmicenje.setToolTipText("");

        lblid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblid.setText("Godina");

        tfGodina.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblid)
                        .addGap(18, 18, 18)
                        .addComponent(tfGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(comboSC, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboTakmicenje, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnDodaj4)
                        .addGap(18, 18, 18)
                        .addComponent(btnOdustani1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboTakmicenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(tfGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj4)
                    .addComponent(btnOdustani1))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodaj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodaj4ActionPerformed
        SportskiCentar sc = (SportskiCentar) comboSC.getSelectedItem();
        Takmicenje t = (Takmicenje) comboTakmicenje.getSelectedItem();
        LokacijeTakmicenja lt = new LokacijeTakmicenja(t, sc, Integer.parseInt(tfGodina.getText()));
        Kontroler.getInstance().dodajLokTakm(lt);
        this.dispose();
    }//GEN-LAST:event_btnDodaj4ActionPerformed

    private void btnOdustani1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustani1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustani1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj1;
    private javax.swing.JButton btnDodaj2;
    private javax.swing.JButton btnDodaj3;
    private javax.swing.JButton btnDodaj4;
    private javax.swing.JButton btnOdustani1;
    private javax.swing.JComboBox<SportskiCentar> comboSC;
    private javax.swing.JComboBox<Takmicenje> comboTakmicenje;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField tfGodina;
    // End of variables declaration//GEN-END:variables
    
    private void popuniComboSc() {
        List<SportskiCentar> lsc = Kontroler.getInstance().vratiCentre();
        for (SportskiCentar sc:lsc) {
            comboSC.addItem(sc);
        }
    }

    private void popuniComboTakmicenja() {
        List<Takmicenje> taks = Kontroler.getInstance().vratiTakmicenja();
        for (Takmicenje t : taks) {
            comboTakmicenje.addItem(t);
        }
    }
}
