/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import logika.Kontroler;
import domen.*;
import java.util.List;
import tablemodels.ModelTabelePrijave;

/**
 *
 * @author Nemanja
 */
public class FormaPrijave extends javax.swing.JFrame {
    
    private Kontroler kontroler;
    private static ModelTabelePrijave mtp;
    /**
     * Creates new form FormaPrijave
     */
    public FormaPrijave() {
        initComponents();
        kontroler = Kontroler.getInstance();
        mtp = new ModelTabelePrijave(kontroler.vratiPrijave());
        jTable2.setModel(mtp);
        popuniComboKlubovi();
        popuniComboTakmicenja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboKlub = new javax.swing.JComboBox<>();
        btnFiltriraj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboTakmicenje = new javax.swing.JComboBox<>();
        btnPrijava = new javax.swing.JButton();
        btnObrisi2 = new javax.swing.JButton();
        btnAzuriraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 202));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setText("Prijave");

        jTable2.setBackground(new java.awt.Color(255, 227, 100));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable2.setSelectionForeground(new java.awt.Color(255, 204, 0));
        jScrollPane2.setViewportView(jTable2);

        btnDodaj.setBackground(new java.awt.Color(255, 204, 0));
        btnDodaj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDodaj.setText("Kreiraj prijavu");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Klub:");

        comboKlub.setToolTipText("");

        btnFiltriraj.setBackground(new java.awt.Color(255, 204, 0));
        btnFiltriraj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFiltriraj.setText("Filtriraj");
        btnFiltriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrirajActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Takmičenje:");

        comboTakmicenje.setToolTipText("");

        btnPrijava.setBackground(new java.awt.Color(255, 204, 0));
        btnPrijava.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrijava.setText("PRIKAZ PRIJAVE");
        btnPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijavaActionPerformed(evt);
            }
        });

        btnObrisi2.setBackground(new java.awt.Color(255, 204, 0));
        btnObrisi2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnObrisi2.setText("Obriši prijavu");
        btnObrisi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisi2ActionPerformed(evt);
            }
        });

        btnAzuriraj.setBackground(new java.awt.Color(255, 204, 0));
        btnAzuriraj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAzuriraj.setText("Ažuriraj prijavu");
        btnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboTakmicenje, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboKlub, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAzuriraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboKlub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltriraj))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboTakmicenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrijava))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnObrisi2)
                        .addGap(32, 32, 32)
                        .addComponent(btnDodaj)
                        .addGap(31, 31, 31)
                        .addComponent(btnAzuriraj)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        DijalogPrijava dp = new DijalogPrijava(this, rootPaneCheckingEnabled, null);
        dp.setVisible(true);
        osveziTabeluPrijave();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnFiltrirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrirajActionPerformed
        mtp = new ModelTabelePrijave
        (kontroler.filtrirajPrijave(comboKlub.getSelectedItem(),comboTakmicenje.getSelectedItem()));
        jTable2.setModel(mtp);
    }//GEN-LAST:event_btnFiltrirajActionPerformed

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        int izbor = jTable2.getSelectedRow();
        if(izbor==-1){
            JOptionPane.showMessageDialog(this,"Niste izabrali nijednu prijavu!",
                "Greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
        EvidencijaPrijave ep = mtp.get(izbor);
        FormaStavkePrijave fsp = new FormaStavkePrijave(ep);
        fsp.setVisible(true);
    }//GEN-LAST:event_btnPrijavaActionPerformed

    private void btnObrisi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisi2ActionPerformed
        int izbor = jTable2.getSelectedRow();
        if(izbor==-1){
            JOptionPane.showMessageDialog(this,"Niste izabrali nijednu prijavu!",
                "Greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
        EvidencijaPrijave ep = mtp.get(izbor);
        kontroler.izbrisiPrijavu(ep.getIdPrijave());
        osveziTabeluPrijave();
    }//GEN-LAST:event_btnObrisi2ActionPerformed

    private void btnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajActionPerformed
        int izbor = jTable2.getSelectedRow();
        if(izbor==-1){
            JOptionPane.showMessageDialog(this,"Niste izabrali nijednu prijavu!",
                "Greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
        EvidencijaPrijave ep = mtp.get(izbor);
        DijalogPrijava dp = new DijalogPrijava(this, rootPaneCheckingEnabled, ep);
        dp.setVisible(true);
        osveziTabeluPrijave();
    }//GEN-LAST:event_btnAzurirajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPrijave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPrijave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPrijave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPrijave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPrijave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnFiltriraj;
    private javax.swing.JButton btnObrisi2;
    private javax.swing.JButton btnPrijava;
    private javax.swing.JComboBox<PlivackiKlub> comboKlub;
    private javax.swing.JComboBox<Takmicenje> comboTakmicenje;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void osveziTabeluPrijave() {
        mtp = new ModelTabelePrijave(kontroler.vratiPrijave());
        jTable2.setModel(mtp);
    }

    private void popuniComboKlubovi(){
        List<PlivackiKlub> pks = kontroler.vratiKlubove();
        for (PlivackiKlub pk : pks) {
            comboKlub.addItem(pk);
        }
    }
    
    private void popuniComboTakmicenja(){
        List<Takmicenje> taks = kontroler.vratiTakmicenja();
        for (Takmicenje t : taks) {
            comboTakmicenje.addItem(t);
        }
    }
}
