/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domen.*;
import javax.swing.JOptionPane;
import logika.Kontroler;
import tablemodels.ModelTabeleStavke;

/**
 *
 * @author Nemanja
 */
public class FormaStavkePrijave extends javax.swing.JFrame {

    private static EvidencijaPrijave ep;
    private static ModelTabeleStavke mts;
    /**
     * Creates new form FormaStavkePrijave
     */
    public FormaStavkePrijave(EvidencijaPrijave ep) {
        initComponents();
        this.ep = ep;
        lblKlub.setText("Prijava kluba "+ep.getKlub());
        lblTakm.setText("za takmičenje "+ep.getTak());
        mts = new ModelTabeleStavke(Kontroler.getInstance().vratiStavkePrijave(ep));
        jTable2.setModel(mts);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTakm = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnObrisi1 = new javax.swing.JButton();
        btnDodaj1 = new javax.swing.JButton();
        btnIzmeni1 = new javax.swing.JButton();
        lblKlub = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 202));

        lblTakm.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lblTakm.setText(" ");

        jTable2.setBackground(new java.awt.Color(255, 227, 100));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable2.setSelectionForeground(new java.awt.Color(255, 204, 0));
        jScrollPane2.setViewportView(jTable2);

        btnObrisi1.setBackground(new java.awt.Color(255, 204, 0));
        btnObrisi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnObrisi1.setText("Obriši stavku");
        btnObrisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisi1ActionPerformed(evt);
            }
        });

        btnDodaj1.setBackground(new java.awt.Color(255, 204, 0));
        btnDodaj1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDodaj1.setText("Dodaj stavku");
        btnDodaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodaj1ActionPerformed(evt);
            }
        });

        btnIzmeni1.setBackground(new java.awt.Color(255, 204, 0));
        btnIzmeni1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIzmeni1.setText("Izmeni stavku");
        btnIzmeni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeni1ActionPerformed(evt);
            }
        });

        lblKlub.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lblKlub.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTakm)
                    .addComponent(lblKlub)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzmeni1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblKlub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTakm)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnObrisi1)
                        .addGap(29, 29, 29)
                        .addComponent(btnIzmeni1)
                        .addGap(31, 31, 31)
                        .addComponent(btnDodaj1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisi1ActionPerformed
        int izbor = jTable2.getSelectedRow();
        if(izbor==-1){
            JOptionPane.showMessageDialog(this,"Niste izabrali nijednu stavku!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Kontroler.getInstance().izbrisiStavku(mts.get(izbor));
        osveziTabeluStavke();
    }//GEN-LAST:event_btnObrisi1ActionPerformed

    private void btnDodaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodaj1ActionPerformed
        DijalogStavka ds = new DijalogStavka(this, rootPaneCheckingEnabled, null, ep);
        ds.setVisible(true);
        osveziTabeluStavke();
    }//GEN-LAST:event_btnDodaj1ActionPerformed

    private void btnIzmeni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeni1ActionPerformed
        int izbor = jTable2.getSelectedRow();
        if(izbor==-1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijednu stavku!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DijalogStavka ds = new DijalogStavka(this, rootPaneCheckingEnabled, mts.get(izbor), ep);
        ds.setVisible(true);
        osveziTabeluStavke();
    }//GEN-LAST:event_btnIzmeni1ActionPerformed

    private void osveziTabeluStavke(){
        mts = new ModelTabeleStavke(Kontroler.getInstance().vratiStavkePrijave(ep));
        jTable2.setModel(mts);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj1;
    private javax.swing.JButton btnIzmeni1;
    private javax.swing.JButton btnObrisi1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblKlub;
    private javax.swing.JLabel lblTakm;
    // End of variables declaration//GEN-END:variables
}
