/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import logika.Kontroler;
import domen.*;
import tablemodels.ModelTabelePK;

/**
 *
 * @author Nemanja
 */
public class PKForma extends javax.swing.JFrame {

    private static Kontroler kontroler;
    private ModelTabelePK mtpk;
    /**
     * Creates new form PKForma
     */
    public PKForma() {
        initComponents();
        kontroler = Kontroler.getInstance();
        mtpk = new ModelTabelePK(kontroler.vratiKlubove());
        jTable1.setModel(mtpk);
        popuniComboMesta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnFiltriraj = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfKlubFilter = new javax.swing.JTextField();
        btnObrisi = new javax.swing.JButton();
        btnTakmicari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboMesto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 202));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Plivački klubovi");

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 0));

        jTable1.setBackground(new java.awt.Color(255, 227, 100));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setViewportView(jTable1);

        btnFiltriraj.setBackground(new java.awt.Color(255, 204, 0));
        btnFiltriraj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFiltriraj.setText("Filtriraj");
        btnFiltriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrirajActionPerformed(evt);
            }
        });

        btnDodaj.setBackground(new java.awt.Color(255, 204, 0));
        btnDodaj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDodaj.setText("Dodaj klub");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setBackground(new java.awt.Color(255, 204, 0));
        btnIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIzmeni.setText("Izmeni klub");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Naziv kluba:");

        tfKlubFilter.setBackground(new java.awt.Color(255, 255, 204));

        btnObrisi.setBackground(new java.awt.Color(255, 204, 0));
        btnObrisi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnObrisi.setText("Obriši klub");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnTakmicari.setBackground(new java.awt.Color(255, 204, 51));
        btnTakmicari.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnTakmicari.setText("TAKMIČARI KLUBA");
        btnTakmicari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakmicariActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mesto:");

        comboMesto.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(tfKlubFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(56, 56, 56)
                        .addComponent(btnFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btnTakmicari)
                        .addContainerGap(147, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzmeni)
                            .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnObrisi))
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnTakmicari))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnFiltriraj))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfKlubFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnObrisi)
                        .addGap(50, 50, 50)
                        .addComponent(btnIzmeni)
                        .addGap(54, 54, 54)
                        .addComponent(btnDodaj)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        PKDijalog pkd = new PKDijalog(this, true, null);
        pkd.setVisible(true);
        mtpk = new ModelTabelePK(kontroler.vratiKlubove());
        jTable1.setModel(mtpk);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int izbor = jTable1.getSelectedRow();
        if(izbor == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan klub!", 
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        PlivackiKlub sc = mtpk.get(izbor);
        //neadekvantno kad se odradi filter: PlivackiKlub sc = kontroler.vratiKlubove().get(izbor);
        
        int potvrda = JOptionPane.showConfirmDialog(this, 
        "Da li ste sigurni da želite da obrišete klub: " + sc.getNazivKluba() + "?", 
        "Potvrda brisanja", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);
        if (potvrda != JOptionPane.YES_OPTION)  return;
        
        kontroler.izbrisiKlubIzBaze(sc.getIdKluba());    
        mtpk = new ModelTabelePK(kontroler.vratiKlubove());
        jTable1.setModel(mtpk);
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int izbor = jTable1.getSelectedRow();
        if(izbor == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan klub!", 
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        PKDijalog pkd = new PKDijalog(this, true, mtpk.get(izbor));
        pkd.setVisible(true);
        mtpk = new ModelTabelePK(Kontroler.getInstance().vratiKlubove());
        jTable1.setModel(mtpk);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnFiltrirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrirajActionPerformed
        mtpk = new ModelTabelePK(Kontroler.getInstance().filtrirajKlubove(tfKlubFilter.getText(),(Mesto) comboMesto.getSelectedItem()));
        jTable1.setModel(mtpk);
    }//GEN-LAST:event_btnFiltrirajActionPerformed

    private void btnTakmicariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakmicariActionPerformed
        int izbor = jTable1.getSelectedRow();
        if(izbor == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan klub!", 
                    "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        TakmicariForma ft = new TakmicariForma(mtpk.get(izbor));
        ft.setVisible(true);
    }//GEN-LAST:event_btnTakmicariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PKForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PKForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PKForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PKForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PKForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnFiltriraj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnTakmicari;
    private javax.swing.JComboBox<Mesto> comboMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfKlubFilter;
    // End of variables declaration//GEN-END:variables

    public void popuniComboMesta() {
        List<Mesto> mesta = Kontroler.getInstance().vratiMesta();
        for (Mesto m : mesta) {
            comboMesto.addItem(m);
        }
    }
}
