/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import logika.Kontroler;
import domen.*;
import tablemodels.ModelTabeleTakmicari;

/**
 * @author Nemanja
 */

//Rekao profesor da ova forma bude samo za jedan klub. 
//U tabeli da ne bude klub nego kao naslov. Kad se dodaje takmicar moze samo u taj klub.

public class TakmicariForma extends javax.swing.JFrame {

    /**
     * Creates new form TakmicariForma
     */
    private ModelTabeleTakmicari mtt;
    private PlivackiKlub pk;
    
    public TakmicariForma(){
    }

    public TakmicariForma(PlivackiKlub pk) {
        initComponents();
        this.pk=pk;
        mtt = new ModelTabeleTakmicari(Kontroler.getInstance().vratiTakmicareKluba(pk));
        jTable2.setModel(mtt);
        String pom = jLabel3.getText();
        jLabel3.setText(pom+" PK "+pk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnObrisi1 = new javax.swing.JButton();
        btnDodaj1 = new javax.swing.JButton();
        btnIzmeni1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 202));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setText("Takmičari");

        jTable2.setBackground(new java.awt.Color(255, 227, 100));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable2.setSelectionForeground(new java.awt.Color(255, 204, 0));
        jScrollPane2.setViewportView(jTable2);

        btnObrisi1.setBackground(new java.awt.Color(255, 204, 0));
        btnObrisi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnObrisi1.setText("Obriši takmičara");
        btnObrisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisi1ActionPerformed(evt);
            }
        });

        btnDodaj1.setBackground(new java.awt.Color(255, 204, 0));
        btnDodaj1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDodaj1.setText("Dodaj takmičara");
        btnDodaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodaj1ActionPerformed(evt);
            }
        });

        btnIzmeni1.setBackground(new java.awt.Color(255, 204, 0));
        btnIzmeni1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIzmeni1.setText("Izmeni takmičara");
        btnIzmeni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeni1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnObrisi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDodaj1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeni1))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObrisi1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnIzmeni1)
                        .addGap(44, 44, 44)
                        .addComponent(btnDodaj1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodaj1ActionPerformed
        TakmicarDialog td = new TakmicarDialog(this, true, null, pk);
        td.setVisible(true);
        mtt = new ModelTabeleTakmicari(Kontroler.getInstance().vratiTakmicareKluba(pk));
        jTable2.setModel(mtt);
    }//GEN-LAST:event_btnDodaj1ActionPerformed

    private void btnIzmeni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeni1ActionPerformed
        int izbor = jTable2.getSelectedRow();
        if(izbor==-1){
            JOptionPane.showMessageDialog(this,"Niste izabrali nijednog takmicara!", 
                    "Greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Takmicar tak = Kontroler.getInstance().vratiTakmicareKluba(pk).get(izbor);
        TakmicarDialog td = new TakmicarDialog(this, true, tak, pk);
        td.setVisible(true);
        mtt = new ModelTabeleTakmicari(Kontroler.getInstance().vratiTakmicareKluba(pk));
        jTable2.setModel(mtt);
    }//GEN-LAST:event_btnIzmeni1ActionPerformed

    private void btnObrisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisi1ActionPerformed
        int izbor = jTable2.getSelectedRow();
        if(izbor==-1){
            JOptionPane.showMessageDialog(this,"Niste izabrali nijednog takmicara!", 
                    "Greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Takmicar tak = Kontroler.getInstance().vratiTakmicareKluba(pk).get(izbor);
        int odluka = JOptionPane.showConfirmDialog(this, "Da li zelite da obrisete takmicara "+tak,
                "Potvrda brisanja", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(odluka!=JOptionPane.YES_OPTION) return;
        Kontroler.getInstance().izbrisiTakmicara(tak.getIdTakmicar());
        mtt = new ModelTabeleTakmicari(Kontroler.getInstance().vratiTakmicareKluba(pk));
        jTable2.setModel(mtt);
    }//GEN-LAST:event_btnObrisi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakmicariForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakmicariForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakmicariForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakmicariForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakmicariForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj1;
    private javax.swing.JButton btnIzmeni1;
    private javax.swing.JButton btnObrisi1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
